name: Deploy

on:
  push:
    branches:
      - "*"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/VestiaDocs-${{ github.ref == 'refs/heads/main' && 'production' || 'test' }}-GithubRole
          role-duration-seconds: 1200

      - name: install sst
        run: |
          curl -fsSL https://ion.sst.dev/install | bash

      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: true

      - name: sst deploy
        run: |
          sst deploy --stage=${{ github.ref == 'refs/heads/main' && 'production' || 'test' }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
